service: checkmate
frameworkVersion: "4"

provider:
  name: aws
  runtime: provided.al2023
  architecture: arm64
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  logRetentionInDays: 30
  httpApi:
    authorizers:
      httpAuthorizer:
        type: jwt
        scopes: email
        identitySource: $request.header.Authorization
        issuerUrl: !Sub https://cognito-idp.${self:provider.region}.amazonaws.com/${CognitoUserPool}
        audience:
          - !Ref CognitoUserPoolClient

package:
  individually: true
  patterns:
    - "!./**"

functions:
  api:
    handler: api-bootstrap
    package:
      artifact: target/lambda/api-bootstrap/api.zip
    events:
      - httpApi:
          method: GET
          path: /health

  create-user:
    handler: create-user
    package:
      artifact: target/lambda/create-user/create-user.zip
    environment:
      USERS_TABLE: !Ref UsersTable
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt UsersTable.Arn
    events:
      - cognitoUserPool:
          pool: ${self:service}-${self:provider.stage}-user-pool
          existing: true
          trigger: PostConfirmation

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-${self:provider.stage}-user-pool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Schema:
          - Name: email
            Required: true
            Mutable: true
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireUppercase: true
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
        UserAttributeUpdateSettings:
          AttributesRequireVerificationBeforeUpdate:
            - email
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service}-${self:provider.stage}-client
        UserPoolId: !Ref CognitoUserPool
        GenerateSecret: false
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
          - ALLOW_USER_SRP_AUTH
        PreventUserExistenceErrors: ENABLED
        AccessTokenValidity: 1
        IdTokenValidity: 1
        RefreshTokenValidity: 30
        TokenValidityUnits:
          AccessToken: hours
          IdToken: hours
          RefreshToken: days

    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-users-table
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
