org: killian168
service: checkmate
frameworkVersion: "4"

provider:
  name: aws
  region: ${opt:region, 'eu-west-1'}
  memorySize: 128
  timeout: 10
  # ToDo: Change this when localstack supports arm64 on x86-64 architecture.
  # architecture: arm64
  runtime: provided.al2023

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local

package:
  individually: true

functions:
  api:
    handler: checkmateAPI
    package:
      artifact: target/lambda/checkmate/bootstrap.zip
    events:
      - http:
          path: /health
          method: GET
