org: killian168
service: checkmate
frameworkVersion: "4"

provider:
  name: aws
  region: ${opt:region, 'eu-west-1'}
  memorySize: 128
  timeout: 10
  architecture: arm64
  runtime: provided.al2023

package:
  individually: true

functions:
  api:
    handler: checkmateAPI
    package:
      artifact: target/lambda/checkmate/bootstrap.zip
    events:
      - http:
          path: /health
          method: GET
          cors: true
