org: killian168
service: checkmate
frameworkVersion: "4"

provider:
  name: aws
  region: ${opt:region, 'eu-west-1'}
  memorySize: 128
  architecture: arm64
  runtime: provided.al2023
  httpApi:
    cors: true
  websocketApi:
    routeSelectionExpression: $request.body.action
  iam:
    role:
      statements: # ToDo: Tighten this up
        - Effect: Allow
          Action:
            - "dynamodb:*"
          Resource: "*"
        - Effect: Allow
          Action:
            - "execute-api:ManageConnections"
          Resource:
            - "arn:aws:execute-api:*:*:*/*/@connections/*"

package:
  individually: true

functions:
  api:
    name: ${self:service}-${sls:stage}-api
    handler: api
    package:
      artifact: target/lambda/api/api.zip
    events:
      - httpApi:
          path: /health
          method: GET
      - httpApi:
          path: /auth/user
          method: ANY
      - httpApi:
          path: /auth/login
          method: POST
      - httpApi:
          path: /queue/join
          method: POST
      - httpApi:
          path: /queue/leave
          method: POST
    reservedConcurrency: 20
    environment:
      USERS_TABLE: !Ref UsersTable
      QUEUE_TABLE: !Ref QueueTable
      JWT_SECRET: ThisIsMySecret # ToDo: Tighten this up

  queue-processor:
    name: ${self:service}-${sls:stage}-queue-processor
    handler: queue-processor
    package:
      artifact: target/lambda/queue-processor/queue-processor.zip
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt QueueTable.StreamArn
          batchSize: 1
          startingPosition: LATEST
          filterPatterns:
            - eventName: [INSERT]
    environment:
      QUEUE_TABLE: !Ref QueueTable
      GAME_SESSIONS_TABLE: !Ref GameSessionsTable

  websocket-api:
    name: ${self:service}-${sls:stage}-websocket-api
    handler: websocket-api
    package:
      artifact: target/lambda/websocket-api/websocket-api.zip
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
    environment:
      PLAYER_CONNECTIONS_TABLE: !Ref PlayerConnectionsTable

  game-session-notifier:
    name: ${self:service}-${sls:stage}-game-session-notifier
    handler: game-session-notifier
    package:
      artifact: target/lambda/game-session-notifier/game-session-notifier.zip
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt GameSessionsTable.StreamArn
          batchSize: 1
          startingPosition: LATEST
          filterPatterns:
            - eventName: [INSERT]
    environment:
      GAME_SESSIONS_TABLE: !Ref GameSessionsTable

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${sls:stage}-users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: GSI_UserByEmail
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    QueueTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${sls:stage}-queue
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        AttributeDefinitions:
          - AttributeName: queue_rating
            AttributeType: S
          - AttributeName: player_id
            AttributeType: S
        KeySchema:
          - AttributeName: queue_rating
            KeyType: HASH
          - AttributeName: player_id
            KeyType: RANGE

    GameSessionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${sls:stage}-game-sessions
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        AttributeDefinitions:
          - AttributeName: session_id
            AttributeType: S
          - AttributeName: player1_id
            AttributeType: S
          - AttributeName: player2_id
            AttributeType: S
        KeySchema:
          - AttributeName: session_id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: GSI_GameSessionByPlayer1
            KeySchema:
              - AttributeName: player1_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: GSI_GameSessionByPlayer2
            KeySchema:
              - AttributeName: player2_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    PlayerConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${sls:stage}-player-connections
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: player_id
            AttributeType: S
        KeySchema:
          - AttributeName: player_id
            KeyType: HASH
