[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
axum = "0.8.6"
lambda_http = "0.17.0"
tower-http = { version = "0.6.2", features = ["cors"] }
jsonwebtoken = "9.3.1"
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
aws-config = { version = "1.8.2", features = ["behavior-version-latest"] }
aws-sdk-dynamodb = "1.84.0"
chrono = { version = "0.4.41", features = ["serde"] }

[dev-dependencies]
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.11.27", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
