[package]
name = "stream-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
aws_lambda_events = { version = "0.14.0", features = ["dynamodb"] }
lambda_runtime = "0.14.4"
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
serde_json = "1.0"
serde_dynamo = { version = "4.2.14", features = ["aws-sdk-dynamodb+1"] }
aws-sdk-dynamodb = "1.84.0"
