[package]
name = "game-session-notifier"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
aws-config = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
lambda_runtime = { workspace = true }
aws_lambda_events = "0.14.0"
serde = { workspace = true }
serde_json = "1.0"
serde_dynamo = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
